version: "3.4"

services:

  provider:
    image: pactfoundation/pact-stub-server
    entrypoint: ./pact_stub_server.sh
    command: -p 8000 -d pacts -o --insecure-tls
    working_dir: /app
    volumes:
      - ./scripts/pact_stub_server.sh:/app/pact_stub_server.sh
      - ./pacts/:/app/pacts:ro
    healthcheck:
      test: wget -O- -q http://localhost:8000/api/health/ || exit 1

  proxy:
    image: traefik:v2.6
    depends_on:
      consumer:
        condition: service_healthy
      provider:
        condition: service_started
    volumes:
      - ./proxy/:/traefik/:ro
    command:
      - "--configFile=/traefik/conf/static.yaml"
    ports:
      - "${LOCAL_HTTPS_PORT:-8443}:8443"

  cypress:
    build:
      context: .
      dockerfile: docker/e2e.Dockerfile
      args:
        USER: ${USER:-appuser}
    container_name: cypress
    depends_on:
      - proxy
    environment:
      - CYPRESS_BASE_URL=https://proxy:8443
    user: ${USER:-appuser}
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.ts/:/app/cypress.config.ts
